#include "wifi.h"
#include <esp_wifi.h>
#include <esp_event.h>
#include <esp_log.h>
#include <nvs_flash.h>
#include <nvs.h>
#include <string.h>

// wifi_config.h generated by ./setup.sh — contains your WiFi credentials
#if __has_include("wifi_config.h")
#include "wifi_config.h"
#define DEFAULT_SSID WIFI_SSID
#define DEFAULT_PASS WIFI_PASS
#else
#error "wifi_config.h not found. Run: ./setup.sh"
#endif

static const char *TAG = "wifi";

SemaphoreHandle_t wifi_connected_sem = nullptr;

static bool load_creds_from_nvs(char *ssid, size_t ssid_len, char *pass, size_t pass_len) {
    nvs_handle_t h;
    if (nvs_open("wifi", NVS_READONLY, &h) != ESP_OK) return false;
    esp_err_t r = nvs_get_str(h, "ssid", ssid, &ssid_len);
    if (r != ESP_OK) { nvs_close(h); return false; }
    r = nvs_get_str(h, "pass", pass, &pass_len);
    nvs_close(h);
    return (r == ESP_OK);
}

static void event_handler(void *arg, esp_event_base_t base,
                          int32_t id, void *data) {
    if (base == WIFI_EVENT && id == WIFI_EVENT_STA_START) {
        esp_wifi_connect();
    } else if (base == WIFI_EVENT && id == WIFI_EVENT_STA_DISCONNECTED) {
        ESP_LOGW(TAG, "disconnected, reconnecting...");
        esp_wifi_connect();
    } else if (base == IP_EVENT && id == IP_EVENT_STA_GOT_IP) {
        auto *ev = (ip_event_got_ip_t *)data;
        ESP_LOGI(TAG, "connected, IP: " IPSTR, IP2STR(&ev->ip_info.ip));
        if (wifi_connected_sem) {
            xSemaphoreGive(wifi_connected_sem);
        }
    }
}

esp_err_t wifi_init_sta(void) {
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    wifi_connected_sem = xSemaphoreCreateBinary();

    // Load WiFi credentials: NVS first, then defaults
    char ssid[33], pass[65];
    if (!load_creds_from_nvs(ssid, sizeof(ssid), pass, sizeof(pass))) {
        ESP_LOGI(TAG, "No stored WiFi, using defaults");
        strlcpy(ssid, DEFAULT_SSID, sizeof(ssid));
        strlcpy(pass, DEFAULT_PASS, sizeof(pass));
    } else {
        ESP_LOGI(TAG, "Loaded WiFi from NVS: %s", ssid);
    }

    ESP_LOGI(TAG, "SSID='%s'", ssid);

    // Normal STA mode
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    if (esp_netif_create_default_wifi_sta() == nullptr) {
        return ESP_FAIL;
    }

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, event_handler, NULL));

    wifi_config_t wifi_cfg = {};
    strlcpy((char *)wifi_cfg.sta.ssid, ssid, sizeof(wifi_cfg.sta.ssid));
    strlcpy((char *)wifi_cfg.sta.password, pass, sizeof(wifi_cfg.sta.password));
    wifi_cfg.sta.threshold.authmode = WIFI_AUTH_WPA2_PSK;

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_cfg));
    ESP_ERROR_CHECK(esp_wifi_start());
    return ESP_OK;
}
